<?php
namespace Omnicasa\Request\Contact;

use Omnicasa\Request\RequestObject;

class DemandEntry extends RequestObject
{
    const PROPERTIES = [
        'DemandID'             => 'integer',
        'PersonId'             => 'integer',
        'OfficeID'             => 'integer',
        'ConstructionOpen'     => 'boolean',
        'ConstructionSemiOpen' => 'boolean',
        'ConstructionClosed'   => 'boolean',
        'Goal'                 => 'integer',
        'PriceMin'             => 'numeric',
        'PriceMax'             => 'numeric',
        'BedRoomsMin'          => 'integer',
        'BedRoomsMax'          => 'integer',
        'BathRoomsMin'         => 'integer',
        'BathRoomsMax'         => 'integer',
        'ShowerRoomsMin'       => 'integer',
        'ShowerRoomsMax'       => 'integer',
        'NumberOfGaragesMin'   => 'integer',
        'NumberOfGaragesMax'   => 'integer',
        'SurfaceTotalMin'      => 'integer',
        'SurfaceTotalMax'      => 'integer',
        'TerraceTotalMin'      => 'integer',
        'TerraceTotalMax'      => 'integer',
        'LivingTotalMin'       => 'integer',
        'LivingTotalMax'       => 'integer',
        'GardenTotalMin'       => 'integer',
        'GardenTotalMax'       => 'integer',
        'SurfaceStoreMin'      => 'integer',
        'SurfaceStoreMax'      => 'integer',
        'SurfaceOfficeMin'     => 'integer',
        'SurfaceOfficeMax'     => 'integer',
        'Lift'                 => 'boolean',
        'Cellar'               => 'boolean',
        'Terrace'              => 'boolean',
        'Attic'                => 'boolean',
        'Garden'               => 'boolean',
        'Office'               => 'boolean',
        'ParkingsMin'          => 'integer',
        'ParkingsMax'          => 'integer',
        'ParGarMin'            => 'integer',
        'ParGarMax'            => 'integer',
        'Comment'              => 'string',
        'TypeDesc'             => 'string',
        'CityDesc'             => 'string',
        'InnerPlace'           => 'boolean',
        'Street'               => 'string',
        'District'             => 'string',
        'Quiet'                => 'integer',
        'Trade'                => 'integer',
        'School'               => 'integer',
        'Connections'          => 'integer',
        'Budget'               => 'numeric',
        'CurrencyType'         => 'integer',
        'Enddate'              => 'DateTime',
        'PersonDescription'    => 'string',
        'Manager'              => 'integer',
        'DemandRef'            => 'string',
        'Furbished'            => 'boolean',
        'SurfaceGround'        => 'integer',
        'Status'               => 'integer',
        'OriginalId'           => 'integer',
        'SiteId'               => 'integer',
        'ModifiedDate'         => 'DateTime',
        'IsDeleted'            => 'boolean',
        'MaxAppartmentFloor'   => 'integer',
        'MaxBuildingFloor'     => 'integer',
        'NumberOfToiletMin'    => 'integer',
        'OutsideSpace'         => 'boolean',
        'UseGps'               => 'boolean',
        'GpsKm'                => 'numeric',
        'GpsCityName'          => 'string',
        'WebModified'          => 'boolean',
        'GeoGraphicIDs'        => 'string',
        'TypeOfPropertyIDs'    => 'string',
        'Entered'              => 'string',
        'Longitude'            => 'numeric',
        'Latitude'             => 'numeric',
        'Zip'                  => 'string',
    ];
}
