<?php
namespace Omnicasa\Request\Contact;

use Omnicasa\Request\Request;

class DemandRegister2Request extends Request
{
    const ENDPOINT = 'DemandRegister2';

    const PROPERTIES = [
        'ID'                      => 'integer',
        'Name'                    => 'string',
        'FirstName'               => 'string',
        'AddressTitle'            => 'string',
        'Address'                 => 'string',
        'City'                    => 'string',
        'Zip'                     => 'string',
        'CountryID'               => 'integer',
        'Email'                   => 'string',
        'PhoneNumber'             => 'string',
        'Password'                => 'string',
        'TypeOfPropertyIDs'       => ['integer'],
        'GeographicIDs'           => ['integer'],
        'Zips'                    => ['string'],
        'GSM'                     => 'string',
        'Goal'                    => 'integer',
        'Garden'                  => 'boolean',
        'Terrace'                 => 'boolean',
        'Budget'                  => 'numeric',
        'PriceMin'                => 'numeric',
        'PriceMax'                => 'numeric',
        'MinRooms'                => 'integer',
        'MaxRooms'                => 'integer',
        'MinBathRooms'            => 'integer',
        'MaxBathRooms'            => 'integer',
        'MinGarages'              => 'integer',
        'MaxGarages'              => 'integer',
        'MinParkings'             => 'integer',
        'MaxParkings'             => 'integer',
        'UseGps'                  => 'boolean',
        'GpsX'                    => 'numeric',
        'GpsY'                    => 'numeric',
        'GpsKm'                   => 'numeric',
        'GpsCityName'             => 'string',
        'DemandStreet'            => 'string',
        'Comment'                 => 'string',
        'TottalArea'              => 'integer',
        'LivingArea'              => 'integer',
        'GroundArea'              => 'integer',
        'Cellar'                  => 'boolean',
        'SiteId'                  => 'integer',
        'PetsRequired'            => 'boolean',
        'LetterTitle'             => 'string',
        'SourceId'                => 'integer',
        'Purpose'                 => 'integer',
        'IsReceivedEmail'         => 'boolean',
        'Categories'              => 'string',
        'LanguageIdFromParameter' => 'integer',
        'EnvironmentIDs'          => ['integer'],
        'Fax'                     => 'string',
        'Lift'                    => 'boolean',
        'IsAlwaysCreatedDemand'   => 'boolean',
        'BoxNr'                   => 'string',
        'IsAnnuity'               => 'boolean',
        'DemandRegion'            => 'Omnicasa\Request\Contact\DemandRegion',
        'GeoCityIds'              => ['integer'],
        'RegionIds'               => ['integer'],
        'LanguageId'              => 'integer',
        'OfficeID'                => 'integer',
    ];
}
