<?php
namespace Omnicasa\Request\Property;

use Omnicasa\Request\RequestObject;

class CountPropertyCondition extends RequestObject
{
    const PROPERTIES = [
        'IDs'                => ['integer'],
        'Status'             => ['integer'],
        'Goal'               => 'integer',
        'WebIDs'             => ['integer'],
        'SiteID'             => 'integer',
        'PersonID'           => 'integer',
        'SelectedByPersonID' => 'integer',
        'BuildingID'         => 'integer',
        'ProjectID'          => 'integer',
        'Marquees'           => ['integer'],
        'SkipMarqueeList'    => 'boolean',
        'MainTypeIDs'        => ['integer'],
        'MainEnviromentIDs'  => ['integer'],
        'EnviromentIDs'      => ['integer'],
        'OZAAMIDs'           => ['integer'],
        'ConditionIDs'       => ['integer'],
        'IsInConditionOrNot' => 'boolean',
        'PortalSiteIDs'      => ['string'],
        'Zips'               => ['string'],
        'StreetName'         => 'string',
        'StreetOperator'     => 'integer',
        'Number'             => 'string',
        'CityNames'          => ['string'],
        'GeoGraphicIDs'      => ['integer'],
        'MainGeoGraphicIDs'  => ['integer'],
        'CountryIDs'         => ['integer'],
        'IsInCountryOrNot'   => 'boolean',
        'ChangeSince'        => 'DateTime',
        'ContractStartSince' => 'DateTime',
        'MinRoom'            => 'integer',
        'MaxRoom'            => 'integer',
        'MinBathRoom'        => 'integer',
        'MaxBathRoom'        => 'integer',
        'PriceFrom'          => 'numeric',
        'PriceTo'            => 'numeric',
        'IncludePriceZero'   => 'boolean',
        'GpsRadius'          => 'numeric',
        'GpsX'               => 'float',
        'GpsY'               => 'float',
        'GpsAddress'         => 'string',
        'IsOffice'           => 'boolean',
        'IsConstruction'     => 'boolean',
        'HasViager'          => 'boolean',
        'HasFurnished'       => 'boolean',
        'HasGarden'          => 'boolean',
        'HasGarage'          => 'boolean',
        'HasTerrace'         => 'boolean',
        'HasLift'            => 'boolean',
        'HasCellar'          => 'boolean',
        'HasParking'         => 'boolean',
        'HasAttic'           => 'boolean',
        'PetsAllowed'        => 'boolean',
        'UseRandom'          => 'boolean',
        'RandomValue'        => 'integer',
        'MinSurface'         => 'integer',
        'MaxSurface'         => 'integer',
        'LivingArea'         => 'integer',
        'ViagerType'         => 'integer',
        'RecordFile'         => 'string',
        'RecordFiles'        => ['string'],
        'AtticIDs'           => ['integer'],
        'EncodePolygonPath'  => 'string',
        'OfficeID'           => 'integer',
        'Keyword'            => 'string',
    ];
}
