<?php
namespace Omnicasa\Request\Property;

use Omnicasa\Request\Request;

class GetPropertyListRequest extends Request
{
    const ENDPOINT = 'GetPropertyList';

    const PROPERTIES = [
        'ProjectIsPublishInternet'     => 'boolean',
        'ProjectIsPublishWebsite'      => 'boolean',
        'Status'                       => ['integer'],
        'Goal'                         => 'integer',
        'MinRoom'                      => 'integer',
        'MaxRoom'                      => 'integer',
        'MinBathRoom'                  => 'integer',
        'MaxBathRoom'                  => 'integer',
        'HasViager'                    => 'boolean',
        'ViagerType'                   => 'integer',
        'MarqueeIDs'                   => ['integer'],
        'SkipMarqueeList'              => ['integer'],
        'WebIDs'                       => ['integer'],
        'Zips'                         => ['string'],
        'CityNames'                    => ['string'],
        'GeoGraphicIDs'                => ['integer'],
        'MainGeoGraphicIDs'            => ['integer'],
        'IsMainGeographicRecursive'    => 'boolean',
        'CountryIDs'                   => ['integer'],
        'IsInCountryOrNot'             => 'boolean',
        'RecordFile'                   => 'string',
        'RecordFiles'                  => ['string'],
        'PriceFrom'                    => 'numeric',
        'PriceTo'                      => 'numeric',
        'IncludePriceZero'             => 'boolean',
        'MinSurface'                   => 'integer',
        'MaxSurface'                   => 'integer',
        'HasGarden'                    => 'boolean',
        'HasGarage'                    => 'boolean',
        'HasTerrace'                   => 'boolean',
        'HasFurnished'                 => 'boolean',
        'HasAttic'                     => 'boolean',
        'HasLift'                      => 'boolean',
        'HasCellar'                    => 'boolean',
        'HasParking'                   => 'boolean',
        'AtticIDs'                     => ['integer'],
        'PersonID'                     => 'integer',
        'SelectedByPersonID'           => 'integer',
        'SiteID'                       => 'integer',
        'ConditionIDs'                 => ['integer'],
        'IsInConditionOrNot'           => 'boolean',
        'LivingArea'                   => 'integer',
        'IsOffice'                     => 'boolean',
        'IsConstruction'               => 'boolean',
        'BuildingID'                   => 'integer',
        'ProjectID'                    => 'integer',
        'GpsAddress'                   => 'string',
        'GpsRadius'                    => 'numeric',
        'GpsX'                         => 'float',
        'GpsY'                         => 'float',
        'EncodePolygonPath'            => 'string',
        'UseRandom'                    => 'boolean',
        'ChangeSince'                  => 'DateTime',
        'MainTypeIDs'                  => ['integer'],
        'IsMainTypeRecursive'          => 'boolean',
        'StreetName'                   => 'string',
        'StreetOperator'               => 'integer',
        'Number'                       => 'string',
        'ContractStartSince'           => 'DateTime',
        'PetsAllowed'                  => 'boolean',
        'RandomValue'                  => 'integer',
        'AddCompositionField'          => 'boolean',
        'OZAAMIDs'                     => ['integer'],
        'MainEnviromentIDs'            => ['integer'],
        'ProvinceIDs'                  => ['integer'],
        'Keyword'                      => 'string',
        'IDs'                          => ['integer'],
        'PortalSiteIDs'                => ['integer'],
        'IsRemovedFontFamily'          => 'boolean',
        'EnviromentIDs'                => ['integer'],
        'IsPropertySelection'          => 'boolean',
        'PropertySelectionNames'       => ['string'],
        'GPSSort'                      => 'string',
        'ProjectStatus'                => ['integer'],
        'GeoCityIds'                   => ['integer'],
        'RegionIds'                    => ['integer'],
        'IsSentReport'                 => 'boolean',
        'IsPublishedAllDocumentStatus' => 'boolean',
        'SkipSiteIds'                  => ['integer'],
        'DisplayFields'                => ['string'],
        'SortFields'                   => ['string'],
        'Limit1'                       => 'integer',
        'Limit2'                       => 'integer',
        'LanguageId'                   => 'integer',
        'DescriptionLanguageId'        => 'integer',
        'OfficeID'                     => 'integer',
    ];
}
